### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by chapulina** [colcon/colcon-sanitizer-reports#21]
We're putting together a dashboard with CI status for some colcon packages and noticed that this repository is not running CI. It would be great if Travis and Appveyor were setup, to keep the pattern of other packages. You can use [colcon-core](https://github.com/colcon/colcon-core) as an example. Thanks! :bowing_woman:

**Comment by dirk-thomas** [comment]
We are using the existing Azure badge. So I will go ahead and close this ticket.

But I have one question: why do the URLs start with `https://dev.azure.com/osrf/colcon-sanitizer-reports/...` - in particular why is `osrf` part of the URL even though the GitHub org unit is `colcon`?

**Comment by dirk-thomas** [comment]
> why do the URLs start with `https://dev.azure.com/osrf/colcon-sanitizer-reports/...` - in particular why is `osrf` part of the URL even though the GitHub org unit is `colcon`?

@thomas-moulard @piraka9011 Can you please answer this question?

**Comment by piraka9011** [comment]
I haven't setup the CI so I don't have any context. Will ask around and see if I can get you an answer.

**Comment by piraka9011** [comment]
This pipeline was apparently setup by @nuclearsandwich so he probably has more context.

**Comment by nuclearsandwich** [comment]
> why is `osrf` part of the URL even though the GitHub org unit is `colcon`?

Because I set the CI up using the OSRF Azure account. If that's a problem then a colcon account needs to be created with Azure, but the right course of action is probably to drop AzureDevOps in favor of GitHub Actions.

**Comment by dirk-thomas** [comment]
Thanks for clarifying. I was mostly curious. The move to GitHub actions sounds like the logic choice for the maintainers of this repo (not a  priority).
